#!/usr/bin/env python3
"""Every figure, generated by committed code from results/all_results.json.

Colourblind-safe palette (Okabe-Ito). No chartjunk. Every axis labelled with
units. PNG at 300 dpi and PDF for each.
"""
from __future__ import annotations
import json, textwrap
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO = Path(__file__).resolve().parent.parent
R = json.loads((REPO/"results"/"all_results.json").read_text(encoding="utf-8"))
EC = json.loads((REPO/"results"/"editor_consistency.json").read_text(encoding="utf-8"))
P1 = json.loads((REPO/"data"/"derived"/"phase1_supplement.json").read_text(encoding="utf-8"))
FIG = REPO/"figures"; FIG.mkdir(exist_ok=True)

# Okabe-Ito, colourblind-safe
CB = ["#0072B2", "#E69F00", "#009E73", "#D55E00", "#CC79A7", "#56B4E9", "#F0E442", "#000000"]
plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False,
                     "figure.dpi": 110, "axes.grid": True, "grid.alpha": 0.25,
                     "grid.linestyle": ":"})

def save(fig, name, caption):
    fig.tight_layout()
    fig.savefig(FIG/f"{name}.png", dpi=300, bbox_inches="tight")
    fig.savefig(FIG/f"{name}.pdf", bbox_inches="tight")
    (FIG/f"{name}.caption.txt").write_text(textwrap.fill(caption, 88)+"\n", encoding="utf-8")
    plt.close(fig)
    print(f"  {name}.png / .pdf")

# ---- F1  the exclusion surface -------------------------------------------
fig, ax = plt.subplots(1, 2, figsize=(9, 3.6))
c = R["corpus"]
ax[0].bar(["kept\npairs", "dropped\ntokens"], [c["tokens_kept"], c["tokens_dropped"]],
          color=[CB[2], CB[3]])
for i, v in enumerate([c["tokens_kept"], c["tokens_dropped"]]):
    ax[0].text(i, v, f"{v:,}", ha="center", va="bottom")
ax[0].set_ylabel("whitespace tokens containing '('")
ax[0].set_title("a. every paren-bearing token is accounted for")
fm = R["exclusions"]["first_match_counts"]
ks = sorted(fm, key=lambda k: -fm[k])[:6]
ax[1].barh([k.replace("_", "\n") for k in ks][::-1], [fm[k] for k in ks][::-1], color=CB[0])
ax[1].set_xscale("log"); ax[1].set_xlabel("tokens dropped (log scale)")
ax[1].set_title("b. why they were dropped")
save(fig, "F1_exclusion_surface",
     "F1. The exclusion surface. (a) Of 1,767,028 whitespace tokens containing an opening "
     "parenthesis, 1,424,314 became pairs and 342,714 were dropped; the accounting closes with "
     "zero residual. (b) First-match counts by reason, log scale. Shows what the filter removed, "
     "NOT whether removal was correct — that is F2.")

# ---- F2  ordering artifact + pooled bias ---------------------------------
fig, ax = plt.subplots(1, 2, figsize=(9.5, 3.8))
fm = R["exclusions"]["first_match_counts"]; tm = R["exclusions"]["true_membership_counts"]
keys = ["editorial_marker_paren", "greek_script", "unbalanced_parens", "no_letters_outside_parens"]
x = np.arange(len(keys)); w = 0.38
ax[0].bar(x-w/2, [fm[k] for k in keys], w, label="published (first-match)", color=CB[0])
ax[0].bar(x+w/2, [tm[k] for k in keys], w, label="true membership", color=CB[1])
ax[0].set_xticks(x); ax[0].set_xticklabels([k.replace("_", "\n") for k in keys], fontsize=7)
ax[0].set_ylabel("tokens"); ax[0].legend(fontsize=7)
ax[0].set_title("a. ordering undercounts two categories")
tv = R["exclusions"]["tvd_null"]
names = [k for k in tv if tv[k]["n"] >= 300]
ratio = [tv[k]["observed_tvd"]/tv[k]["null_p95"] for k in names]
order = np.argsort(ratio)
ax[1].barh([names[i].replace("_", "\n") for i in order], [ratio[i] for i in order],
           color=[CB[3] if ratio[i] > 3 else CB[5] for i in order])
ax[1].axvline(1.0, color="k", lw=1, ls="--")
ax[1].set_xlabel("observed TVD ÷ bootstrap null p95  (1.0 = indistinguishable from noise)")
ax[1].tick_params(labelsize=7)
ax[1].set_title("b. which exclusions really are skewed")
save(fig, "F2_ordering_and_bias",
     "F2. Two corrections to the exclusion audit. (a) The filter chain is first-match, so "
     "published counts understate categories tested late: editorial_marker_paren by 50%, "
     "greek_script by 22%. (b) Total variation distance against a bootstrap null at each "
     "category's own n. Values near 1.0 are indistinguishable from sampling noise; an absolute "
     "threshold would have called several of them skewed. Does not show whether excluding a "
     "category is correct, only whether the excluded set differs distributionally.")

# ---- F3  the symbol inventory --------------------------------------------
import unicodedata, re
def fam(w):
    w = w.lower().rstrip("?!")
    if w.startswith(("mulier", "muleris", "muileris", "umulier", "gaia")): return "reversed C\n(mulieris/Gaiae)"
    if w.startswith(("centur", "centvr", "cenur", "centnar", "centen", "centir", "curia", "centum")): return "centurial sign"
    if w.startswith(("denar", "dena", "sestert", "sertert", "dupond", "assem", "asses", "solid", "siliqu")): return "monetary sign"
    if any(unicodedata.name(ch, "").startswith("GREEK") for ch in w if ch.isalpha()): return "Greek measures"
    if w.startswith(("mil", "mll", "mii", "milli")): return "milliary sign"
    if w.startswith(("obit", "obiit", "periit", "mortu")): return "obitus (Θ)"
    if w in ("crux", "christus", "christo", "omega", "dis"): return "Christian signs"
    if not w: return "unresolved |()"
    return "fractions/weights\n& other"
from collections import Counter
famc = Counter(); famf = Counter()
for f, n in P1["pipe_forms"].items():
    w = f[f.index("(")+1:-1]
    k = fam(w); famc[k] += n; famf[k] += 1
fig, ax = plt.subplots(figsize=(7.2, 4))
ks = [k for k, _ in famc.most_common()]
ax.barh(ks[::-1], [famc[k] for k in ks][::-1], color=CB[0])
for i, k in enumerate(ks[::-1]):
    ax.text(famc[k], i, f"  {famc[k]:,}  ({famf[k]} forms)", va="center", fontsize=7)
ax.set_xlabel("occurrences in the corpus")
ax.set_xlim(0, max(famc.values())*1.35)
ax.set_title(f"One ASCII '|' stands for at least {len(famc)} distinct epigraphic signs\n"
             f"{R['symbol_inventory']['distinct_pipe_forms']} distinct forms, "
             f"{R['symbol_inventory']['total_occurrences']:,} occurrences", fontsize=9)
save(fig, "F3_symbol_inventory",
     "F3. The |(...) inventory. EDCS renders non-typeable epigraphic signs as a single ASCII "
     "pipe, collapsing at least eight unrelated glyphs onto one character. Grouping into "
     "families is a rule-based pass over surface strings and needs philological confirmation; "
     "the 376-form enumeration with counts does not depend on it.")

# ---- F4  the vinculum census ---------------------------------------------
fig, ax = plt.subplots(figsize=(7.4, 3.6))
v = R["vinculum"]
labels = ["total\ncharacters", "all combining\nmarks", "U+0305\noverline", "U+0304\nmacron",
          "Number Forms\nblock", "Ancient Symbols\nblock"]
vals = [v["total_chars"], v["all_combining_marks_total"],
        v["named"]["U+0305 COMBINING OVERLINE"]["occurrences"],
        max(v["named"]["U+0304 COMBINING MACRON"]["occurrences"], 0.4),
        max(v["unicode_blocks"].get("Number Forms U+2150-U+218F", 0), 0.4),
        max(v["unicode_blocks"].get("Ancient Symbols U+10190-U+101CF", 0), 0.4)]
cols = [CB[7], CB[0], CB[3], CB[3], CB[3], CB[3]]
ax.bar(labels, vals, color=cols)
ax.set_yscale("log"); ax.set_ylabel("occurrences (log scale)")
for i, (l, val) in enumerate(zip(labels, vals)):
    txt = "0" if val == 0.4 else f"{int(val):,}"
    ax.text(i, val, txt, ha="center", va="bottom", fontsize=8)
ax.tick_params(labelsize=7)
ax.set_title("The vinculum is not preserved in EDCS plain text", fontsize=9)
save(fig, "F4_vinculum_census",
     "F4. Full character census of all 588,509 records. The multiplicative vinculum has zero "
     "attestations; U+0305 occurs twice and U+0304 not at all, in 39,470,885 characters. "
     "Unicode provides dedicated code points for the reversed C and the Roman denarius signs "
     "(Number Forms, Ancient Symbols) and EDCS uses neither. Bars at 0 are drawn at a nominal "
     "height for visibility on a log axis.")

# ---- F5  circularity ------------------------------------------------------
fig, ax = plt.subplots(figsize=(6.8, 3.6))
h = {float(k): vv for k, vv in R["exclusions"]["restored_fraction_hist"].items()}
xs = sorted(h); ys = [h[k] for k in xs]
ax.bar(xs, ys, width=0.085, color=[CB[3] if k == 1.0 else CB[0] for k in xs])
ax.set_xlabel("share of the abbreviation's letters supplied by the editor")
ax.set_ylabel("tokens")
ax.set_title(f"{R['circularity']['fully_editorial_pct']}% of bracket-excluded abbreviations\n"
             f"are wholly the editor's supplement", fontsize=9)
save(fig, "F5_circularity",
     "F5. Circularity as a measured quantity. For every token excluded as bracket markup, the "
     "share of the abbreviation's own letters that lie inside an editorial restoration. 63.25% "
     "are wholly editorial and only 1.35% are fully attested, so the 253,256 'recoverable' "
     "tokens shrink to 3,401 under the strictest reading. Applies to EXCLUDED tokens; every "
     "kept pair sits outside brackets and scores 0.0.")

# ---- F6  the experiment ---------------------------------------------------
fig, ax = plt.subplots(figsize=(7.2, 4))
conds = ["C1", "C2", "C3"]
for i, (m, lab) in enumerate([("M1", "M1 lookup (no text)"), ("M2", "M2 linear (reads text)"),
                              ("M3", "M3 LaBerta (reads text)")]):
    ys, es = [], []
    for c in conds:
        k = f"{m}_{c}"
        if k not in R["models"]: ys.append(np.nan); es.append(0); continue
        s = R["models"][k]["sets"]["primary_test"]
        ys.append(s["accuracy_mean"]); es.append(s["accuracy_std"])
    ax.errorbar(conds, ys, yerr=es, marker="o", capsize=4, color=CB[i], label=lab, lw=2)
ax.set_ylabel("accuracy on primary_test")
ax.set_xlabel("context condition   (C1 text only · C2 +province · C3 +province +century)")
ax.legend(fontsize=8); ax.set_title("Province and century help only a model that cannot read the text", fontsize=9)
save(fig, "F6_context_conditions",
     "F6. The C1→C2→C3 experiment, mean ± SD over seeds. M1 gains 8.3 points from province and "
     "century because it has no other information. M2 and M3 both lose 0.70 points — a linear "
     "re-ranker and a 137M-parameter Latin transformer agree to four decimals. M3 is one seed "
     "and trained on 100k rows (9% of the training split), so its error bar is absent and its "
     "level understates what full training would give.")

# ---- F7  memorisation vs transfer ----------------------------------------
fig, ax = plt.subplots(figsize=(7.2, 4))
w = 0.35; x = np.arange(3)
seen = [R["models"][f"M1_{c}"]["sets"]["primary_test"]["accuracy_mean"] for c in conds]
unseen = [R["models"][f"M1H_{c}"]["sets"]["heldout_province_test"]["accuracy_mean"] for c in conds]
ax.bar(x-w/2, seen, w, label="provinces seen in training", color=CB[0])
ax.bar(x+w/2, unseen, w, label="provinces never seen", color=CB[3])
for i in range(3):
    ax.text(i-w/2, seen[i], f"{seen[i]:.3f}", ha="center", va="bottom", fontsize=7)
    ax.text(i+w/2, unseen[i], f"{unseen[i]:.3f}", ha="center", va="bottom", fontsize=7)
ax.set_xticks(x); ax.set_xticklabels(conds)
ax.set_ylabel("accuracy"); ax.legend(fontsize=8)
ax.set_title("The province signal is memorised, not learned\n"
             "+8.3 points on provinces seen in training, +0.0000 on provinces withheld", fontsize=9)
save(fig, "F7_memorisation_vs_transfer",
     "F7. M1 with and without the withheld provinces in training. On provinces seen in training "
     "the province conditioning is worth 8.3 points. On Britannia, Mauretania Caesariensis and "
     "Pannonia inferior, withheld entirely, it is worth exactly zero to four decimal places: "
     "the conditional lookup table is empty for an unseen province, so C2 and C3 back off to C1. "
     "The gain is memorisation of local distributions, not a transferable property of Latin.")

# ---- F8  cost / performance ----------------------------------------------
fig, ax = plt.subplots(figsize=(6.8, 4))
for i, m in enumerate(["M1", "M2", "M3"]):
    k = f"{m}_C1"
    if k not in R["models"]: continue
    mm = R["models"][k]
    t = max(mm["train_seconds_mean"], 0.5)
    ax.scatter(t, mm["sets"]["primary_test"]["accuracy_mean"], s=90, color=CB[i], zorder=3)
    ax.annotate(f"{m}\n{mm['param_count']:,} params",
                (t, mm["sets"]["primary_test"]["accuracy_mean"]),
                textcoords="offset points", xytext=(9, -4), fontsize=8)
ax.set_xscale("log"); ax.set_xlabel("training wall-clock time, seconds (log scale)")
ax.set_ylabel("accuracy on primary_test (C1)")
ax.set_title("A linear model recovers 97% of a Latin transformer's accuracy", fontsize=9)
save(fig, "F8_cost_performance",
     "F8. Accuracy against training cost at C1. M2 reaches 97.3% of M3's accuracy with 1/130th "
     "the parameters and 1/14th the training time. M3 was trained on 100k rows against M2's "
     "1.14M, which understates M3 — the comparison favours the cheap model and should be read "
     "with that caveat.")

# ---- F9  editorial label noise -------------------------------------------
fig, ax = plt.subplots(1, 2, figsize=(9, 3.4))
a = EC["A_identical_context_different_expansion"]
ax[0].bar(["consistent", "editors\ndisagree"],
          [R["corpus"]["extracted_pairs"]-a["rows_involved"], a["rows_involved"]],
          color=[CB[2], CB[3]])
ax[0].set_yscale("log"); ax[0].set_ylabel("rows (log scale)")
ax[0].set_title(f"a. label noise floor: {100*a['share_of_task_rows']:.2f}%", fontsize=9)
cc = EC["C_boundary_is_editorial"]["examples"]
top = list(cc.items())[:8]
y = np.arange(len(top))
ax[1].barh(y-0.2, [d["as_expansion"] for _, d in top], 0.4, label="as an expansion", color=CB[0])
ax[1].barh(y+0.2, [d["as_plain_text"] for _, d in top], 0.4, label="carved in full", color=CB[1])
ax[1].set_yticks(y); ax[1].set_yticklabels([w for w, _ in top], fontsize=7)
ax[1].invert_yaxis(); ax[1].set_xlabel("occurrences"); ax[1].legend(fontsize=7)
ax[1].set_title("b. the same word, abbreviated or not", fontsize=9)
save(fig, "F9_editorial_noise",
     "F9. (a) 13,706 rows (0.96%) carry an expansion that differs from another row with a "
     "byte-identical 80-character context — same evidence, different editorial call. A floor, "
     "not the true rate. (b) 66.4% of expansion forms also occur as uncontracted plain text. "
     "This is variation between stones, not editorial inconsistency; it shows the task is "
     "conditioned on the editor having judged an abbreviation present.")

# ---- F10  test set difficulty and ceilings -------------------------------
fig, ax = plt.subplots(figsize=(7.6, 4))
sets = ["primary_test", "test_no_context_duplicate", "test_lexical_only", "test_lexical_hard",
        "test_rare_form", "test_unseen_form"]
mm = R["models"].get("M2_C1", {}).get("sets", {})
acc = [mm.get(s, {}).get("accuracy_mean", np.nan) for s in sets]
ceil = [mm.get(s, {}).get("ceiling", np.nan) for s in sets]
y = np.arange(len(sets))
ax.barh(y, ceil, 0.6, color="#DDDDDD", label="ceiling (candidate ranking)")
ax.barh(y, acc, 0.6, color=CB[0], label="M2 accuracy")
ax.set_yticks(y); ax.set_yticklabels([s.replace("test_", "").replace("_", " ") for s in sets], fontsize=8)
ax.invert_yaxis(); ax.set_xlabel("accuracy"); ax.legend(fontsize=8, loc="lower right")
ax.set_title("Each test set, against the ceiling the design imposes", fontsize=9)
save(fig, "F10_testset_ceilings",
     "F10. M2 accuracy per test set against the ceiling imposed by candidate ranking, which can "
     "only propose expansions seen for that key in training. test_unseen_form has a ceiling of "
     "exactly zero and is unanswerable by construction; test_rare_form caps at 0.481. Reporting "
     "accuracy without the ceiling would misrepresent every set below the first two.")

print(f"\n{len(list(FIG.glob('*.png')))} figures written to figures/")
